// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateDeck(arg1, arg2, arg3) {
  return window['go']['api']['DeckImpl']['CreateDeck'](arg1, arg2, arg3);
}

export function DeleteDeck(arg1) {
  return window['go']['api']['DeckImpl']['DeleteDeck'](arg1);
}

export function ExportDeck(arg1, arg2) {
  return window['go']['api']['DeckImpl']['ExportDeck'](arg1, arg2);
}

export function GetAllDecks() {
  return window['go']['api']['DeckImpl']['GetAllDecks']();
}

export function GetDeck(arg1) {
  return window['go']['api']['DeckImpl']['GetDeck'](arg1);
}

export function UpdateDeck(arg1, arg2, arg3, arg4) {
  return window['go']['api']['DeckImpl']['UpdateDeck'](arg1, arg2, arg3, arg4);
}
