// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function CreateDeck(arg1:string,arg2:string,arg3:string):Promise<models.DeckModel>;

export function DeleteDeck(arg1:number):Promise<void>;

export function ExportDeck(arg1:number,arg2:string):Promise<string>;

export function GetAllDecks():Promise<Array<models.DeckModel>>;

export function GetDeck(arg1:number):Promise<models.DeckModel>;

export function UpdateDeck(arg1:number,arg2:string,arg3:string,arg4:string):Promise<models.DeckModel>;
