// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function CreateFlashcard(arg1:number,arg2:string,arg3:string):Promise<models.FlashcardModel>;

export function DeleteFlashcard(arg1:number,arg2:number):Promise<models.FlashcardModel>;

export function GetAllFlashcards(arg1:number):Promise<Array<models.FlashcardModel>>;

export function GetDueFlashcards(arg1:number):Promise<Array<models.FlashcardModel>>;

export function GetFlashcard(arg1:number,arg2:number):Promise<models.FlashcardModel>;

export function ReviewFlashcard(arg1:number,arg2:number,arg3:string):Promise<void>;

export function UpdateFlashcard(arg1:models.FlashcardModel):Promise<models.FlashcardModel>;

export function UpdateGrading(arg1:string):Promise<void>;
