// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {chat} from '../models';

export function GenerateFlashcards(arg1:string,arg2:string,arg3:number):Promise<Array<chat.Flashcard>>;
