// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CleanupRecording() {
  return window['go']['main']['FeynmanService']['CleanupRecording']();
}

export function InitFeynmanService(arg1) {
  return window['go']['main']['FeynmanService']['InitFeynmanService'](arg1);
}

export function StartRecording() {
  return window['go']['main']['FeynmanService']['StartRecording']();
}

export function StopRecordingAndAnalyze() {
  return window['go']['main']['FeynmanService']['StopRecordingAndAnalyze']();
}
