// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {services} from '../models';

export function CleanupRecording():Promise<void>;

export function InitFeynmanService(arg1:string):Promise<void>;

export function StartRecording():Promise<void>;

export function StopRecordingAndAnalyze():Promise<services.FeynmanAnalysis>;
