// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateFlashcard(arg1, arg2, arg3, arg4) {
  return window['go']['main']['FlashcardImpl']['CreateFlashcard'](arg1, arg2, arg3, arg4);
}

export function DeleteFlashcard(arg1, arg2) {
  return window['go']['main']['FlashcardImpl']['DeleteFlashcard'](arg1, arg2);
}

export function GetAllFlashcards(arg1) {
  return window['go']['main']['FlashcardImpl']['GetAllFlashcards'](arg1);
}

export function GetDueFlashcards(arg1) {
  return window['go']['main']['FlashcardImpl']['GetDueFlashcards'](arg1);
}

export function GetFlashcard(arg1, arg2) {
  return window['go']['main']['FlashcardImpl']['GetFlashcard'](arg1, arg2);
}

export function ReviewFlashcard(arg1, arg2, arg3) {
  return window['go']['main']['FlashcardImpl']['ReviewFlashcard'](arg1, arg2, arg3);
}

export function UpdateFlashcard(arg1) {
  return window['go']['main']['FlashcardImpl']['UpdateFlashcard'](arg1);
}

export function UpdateGrading(arg1) {
  return window['go']['main']['FlashcardImpl']['UpdateGrading'](arg1);
}
