// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function RephraseFlashcard(arg1:number,arg2:number,arg3:number):Promise<models.FlashcardModel>;
