// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function RephraseFlashcard(arg1, arg2, arg3) {
  return window['go']['main']['RephraseService']['RephraseFlashcard'](arg1, arg2, arg3);
}
