// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetOpenAIKey() {
  return window['go']['main']['SettingsService']['GetOpenAIKey']();
}

export function SaveOpenAIKey(arg1) {
  return window['go']['main']['SettingsService']['SaveOpenAIKey'](arg1);
}
